//login
export const GET_LOGIN_PENDING = "GET_LOGIN_PENDING";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";

//register
export const GET_REGISTER_PENDING = "GET_REGISTER_PENDING";
export const GET_REGISTER_SUCCESS = "GET_REGISTER_SUCCESS";
export const GET_REGISTER_ERROR = "GET_REGISTER_ERROR";